name: Fuggix
version: ${project.version}
main: me.twone.fuggix.Fuggix
authors: [ 2021_, Plch ]
description: ${project.description}

commands:
  fuggix:
    description: Main command for Fuggix
    usage: /fuggix
    aliases: [ fg ]
    permission: fuggix.commands
